### PR TITLE
Command Line Interface

### PR DESCRIPTION
**Pull request by laurentpayot**
I added a CLI to get the colors directly in the CSS format so we can simply copy and paste the console output.

### CODE REVIEW

**Comment by leonardorafael** [comment]
A very nice add @laurentpayot  thanks for that.
Can we have different outputs on CLI?
We could start with "json" as default and "css" as a second option.
Let me know if this makes sense for you too.
```
// output as json
material-dynamic-colors "#FF0000"
material-dynamic-colors "#FF0000" json

// output as css
material-dynamic-colors "#FF0000" css

// a future output
material-dynamic-colors "#FF0000" *
```

**Comment by laurentpayot** [comment]
@leonardorafael sure, but how should the JSON keys look like? Kebab case `"--on-primary"` or camel case `"onPrimary"`?

**Comment by leonardorafael** [comment]
> @leonardorafael sure, but how should the JSON keys look like? Kebab case `"--on-primary"` or camel case `"onPrimary"`?

I think camelCase fit best as json

**Comment by laurentpayot** [comment]
The CLI output is now JSON by default. A `css` or `CSS` argument now has to be added for a CSS output. I don’t have the time to implement the `*` argument right now as it introduces more complexity.

**Comment by laurentpayot** [comment]
@leonardorafael by the way the JSON output is actually a JS object output. Did you actually mean a real, one line string JSON output like below?
```json
{"light":{"primary":"#c00100","onPrimary":"#ffffff","primaryContainer":"#ffdad4","onPrimaryContainer":"#410000","secondary":"#775651","onSecondary":"#ffffff","secondaryContainer":"#ffdad4","onSecondaryContainer":"#2c1512","tertiary":"#705c2e","onTertiary":"#ffffff","tertiaryContainer":"#fbdfa6","onTertiaryContainer":"#251a00","error":"#ba1a1a","onError":"#ffffff","errorContainer":"#ffdad6","onErrorContainer":"#410002","background":"#fffbff","onBackground":"#201a19","surface":"#fff8f6","onSurface":"#201a19","surfaceVariant":"#f5ddda","onSurfaceVariant":"#534341","outline":"#857370","outlineVariant":"#d8c2be","shadow":"#000000","scrim":"#000000","inverseSurface":"#362f2e","inverseOnSurface":"#fbeeec","inversePrimary":"#ffb4a8","surfaceDim":"#e4d7d5","surfaceBright":"#fff8f6","surfaceContainerLowest":"#ffffff","surfaceContainerLow":"#fef1ee","surfaceContainer":"#f8ebe9","surfaceContainerHigh":"#f3e5e3","surfaceContainerHighest":"#ede0dd"},"dark":{"primary":"#ffb4a8","onPrimary":"#690100","primaryContainer":"#930100","onPrimaryContainer":"#ffdad4","secondary":"#e7bdb6","onSecondary":"#442925","secondaryContainer":"#5d3f3b","onSecondaryContainer":"#ffdad4","tertiary":"#dec48c","onTertiary":"#3e2e04","tertiaryContainer":"#564419","onTertiaryContainer":"#fbdfa6","error":"#ffb4ab","onError":"#690005","errorContainer":"#93000a","onErrorContainer":"#ffb4ab","background":"#201a19","onBackground":"#ede0dd","surface":"#181211","onSurface":"#ede0dd","surfaceVariant":"#534341","onSurfaceVariant":"#d8c2be","outline":"#a08c89","outlineVariant":"#534341","shadow":"#000000","scrim":"#000000","inverseSurface":"#ede0dd","inverseOnSurface":"#362f2e","inversePrimary":"#c00100","surfaceDim":"#181211","surfaceBright":"#3f3736","surfaceContainerLowest":"#120d0c","surfaceContainerLow":"#201a19","surfaceContainer":"#251e1d","surfaceContainerHigh":"#2f2827","surfaceContainerHighest":"#3b3332"}}
```

**Comment by leonardorafael** [comment]
I think the JS object (instead JSON) is more "usable". Don't you? What do you think?

**Comment by leonardorafael** [comment]
I think the output can return always a JS object like (I'm not sure if is logically ok):

```js
// as js object
{
  dark: {
    primary: null,
    onPrimary: null
    ...
  },
  light: {
    primary: null,
    onPrimary: null
    ...
  }
}

// as css variables
{
  dark: "--primary: null; --on-primary: null;...",
  light: "--primary: null; --on-primary: null;..."
}
```

**Comment by leonardorafael** [comment]
Or we can pass something like:

``` 
// to return light theme
material-dynamic-colors "#FF0000" json|css|js light

// to return dark theme
material-dynamic-colors "#FF0000" json|css|js dark
```

In this case, the result can be a "pure output format" too.

**Comment by laurentpayot** [comment]
> I think the JS object (instead JSON) is more "usable". Don't you? What do you think?

Yes, and if JSON is absolutely needed a simple `JSON.stringify()` of the JS output will do the trick. So nothing to change I think.

**Review by leonardorafael — APPROVED** [review]
👍

**Pull request merged**
